### PR TITLE
Adjust the pagination

### LINKED ISSUE #601: Pagination breaks the UI
**Description**
The page breakes when we have considerably big amount of pages

**Expected result**

Ui should not break when we have multiple pages

**Actual result**

image

**Steps to reproduce**

**Troubleshooting**

### LINKED ISSUE #607: Resources are not displayed in the Role Edit modal
**Description**

**Expected result**

Chosen resources are displayed when editing a Role.

**Actual result**

Chosen resources aren't displayed when editing a Role.

**Steps to reproduce**

1. Create or choose a Role.
2. Click `Edit` button and select Resource from the list e.g. `events`.
3. Click `Update` button.
4. Click `Edit` - chosen Resource is not displayed there.

### PR DESCRIPTION
**Pull request by Wawrzyn321**
**Description**

Changes proposed in this pull request:

- Adjust the pagination to follow [Fiori guidelines](https://sap.github.io/fundamental/components/pagination.html#in-between-more-than-three-pages)
- Make possible to change the pagination size.
- Fix TTL field type (add `min`)
- Fix #607 

**Related issue(s)**

Closes #601 
Closes #607

### CODE REVIEW

File: shared/components/GenericList/Pagination/Pagination.js [hunk 1]
```diff
@@ -30,6 +43,8 @@ export const Pagination = ({
 }) => {
   const pagesCount = Math.ceil(itemsTotal / itemsPerPage);
 
+  const partitions = makePartitions(currentPage, pagesCount);
+
   return (
     <div style={{ display: 'flex', justifyContent: 'center' }}>
```
Comment (akucharska) [inline shared/components/GenericList/Pagination/Pagination.js:49]: It would be nice to have pagination in one line so maybe add `align-items: baseline;` here.

But also colors do not match:
- arrows should be blue
- items and active page are in different color
- there should be no underline

Screen Shot 2021-11-26 at 12 17 27
Screen Shot 2021-11-26 at 12 17 16

**Review by akucharska — CHANGES_REQUESTED** [review]
Nicely done :) 
The only thing I notice are some minor differences in styles

**Review by akucharska — APPROVED** [review]

**Review by majakurcius — APPROVED** [review]
