### PR TITLE
fix: Stop flickering the delete box

### LINKED ISSUE #3721: Delete Module dialog is jumping
**Description**
Delete Module dialog is jumping.

**Expected result**
Delete Module dialog is not jumping.

**Actual result**

https://github.com/user-attachments/assets/eeab50e5-ca76-410d-9724-356a4af76e26

**Steps to reproduce**
1. Go to Modules view
2. Click the trash icon on one of the module
3. Wait a couple seconds

**Troubleshooting**

### PR DESCRIPTION
**Pull request by KonradPietocha**
**Description**

Changes proposed in this pull request:

- Stopping the jumping delete-box.
- Override style to center.

**Related issue(s)**
Closes #3721 

**Definition of done**

- [x] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - revert: Revert commit
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [x] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [x] Explain clearly why you created the PR and what changes it introduces
- [x] All necessary steps are delivered, for example, tests, documentation, merging

### CODE REVIEW

File: src/components/KymaModules/support.ts [hunk 1]
```diff
@@ -224,3 +224,20 @@ export const setChannel = (
...
+  layoutState: { midColumn: { resourceType: string } },
+) => {
+  // Checking if this is the selected module after a refresh or other case after which we have undefined.
+  if (window.location.href.includes('kymamodules') && layoutState?.midColumn) {
+    const resourceType = layoutState.midColumn.resourceType;
+    const resourceTypeDotIndex = resourceType.indexOf('.');
+    const resourceTypeBase =
+      resourceTypeDotIndex !== -1
+        ? resourceType.substring(0, resourceTypeDotIndex)
+        : resourceType;
```
Comment (OliwiaGowor) [inline src/components/KymaModules/support.ts:239]: Would something like this work?
` const [resourceTypeBase] = layoutState.midColumn.resourceType.split('.');`

**Review by OliwiaGowor — COMMENTED** [review]
Could something also be done with the jump when opening the delete dialog or is it UI5 issue? 

https://github.com/user-attachments/assets/37f6f1f3-7aad-460a-b139-7ad5b1b066f3

**Review by OliwiaGowor — APPROVED** [review]
