### PR TITLE
fix: Open category after navigating from another view

### LINKED ISSUE #4320: UXC-026 Side Navigation - Category is not opening after navigation
## 🧩 UxC Vega Review Finding

**Context:**
As part of the **UxC Vega** product standards rollout, the UX team conducted a design review. The following finding requires adjustment to align with the new standards.

---

### 🔍 Finding Summary
**ID:** UXC-014

---

### 🧠 Description
I came to this page from clicking Create in the cluster overview. When navigating the user from somewhere else, expand the parent item in the side navigation so that the user can see where they are located in the app.

---

### 📘 Reference
- **Design spec:** 
   - [Figma findings](https://www.figma.com/board/S23zo8HIqNvf2VuuLOp8ES/UXC-Reviews-2025?node-id=2705-5639&t=igqSHAXBj8bYYLYv-0)
- **Screenshot / Example:**  

Image

### PR DESCRIPTION
**Pull request by OliwiaGowor**
**Description**

Changes proposed in this pull request:

- Open category after navigating from another view

**Related issue(s)**
Closes #4320 

**Definition of done**

- [x] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - revert: Revert commit
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [x] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [x] Explain clearly why you created the PR and what changes it introduces
- [x] All necessary steps are delivered, for example, tests, documentation, merging

### CODE REVIEW

File: src/sidebar/CategoryItem.tsx [hunk 1]
```diff
@@ -73,35 +101,41 @@ export function CategoryItem({
...
 
-  const children = category.items?.map((nn, index) => (
-    <React.Fragment key={`${nn.pathSegment}-${index}`}>
-      {nn.dataSources ? (
-        <DataSourcesContextProvider
-          dataSources={handleEmptyNamespace(nn.dataSources)}
-        >
+  const children = category.items?.map((nn, index) => {
+    const isNodeSelected = checkIsSelected(nn);
+    console.log(isNodeSelected);
```
Comment (awoloszyn22) [inline src/sidebar/CategoryItem.tsx]: console log

**Comment by awoloszyn22** [comment]
I see a TypeScript error in file `src/sidebar/SidebarNavigation.tsx` (missing prop in `NavItem` component)

**Review by awoloszyn22 — APPROVED** [review]
