### PR TITLE
Resolve upload yaml issues

### LINKED ISSUE #975: Deploying a YAML should have a Close button if all is successful
**Description**

In the case all the deployments are successful we should have a Close button instead of Submit and Cancel

**Expected result**

**Actual result**

image

**Steps to reproduce**

**Troubleshooting**

### LINKED ISSUE #976: Deploy Yaml is not responsive
**Description**

When Resizing the screen, the confirmation sidebar does not scale and is impossible to see the progress the confirmation screen.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

image

### PR DESCRIPTION
**Pull request by Wawrzyn321**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

Closes #976 
Closes #975

### CODE REVIEW

File: core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUploadDialog.js [hunk 1]
```diff
@@ -45,35 +55,51 @@ export function YamlUploadDialog({ show, onCancel }) {
...
+    lastOperationState === OPERATION_STATE_SUCCEEDED ? (
+      <Button onClick={onCancel} option="emphasized">
+        {t('common.buttons.close')}
+      </Button>
+    ) : (
+      <>
         <Button
-          onClick={fetchResources}
+          onClick={() => {
+            console.log('?');
```
Comment (dariadomagala) [inline core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUploadDialog.js:69]: Please remove it

File: core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUploadDialog.js [hunk 2]
```diff
@@ -45,35 +55,51 @@ export function YamlUploadDialog({ show, onCancel }) {
     setResourcesWithStatuses(resourcesWithStatus);
     oldYaml.current = yaml;
   };
+  console.log(lastOperationState);
```
Comment (dariadomagala) [inline core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUploadDialog.js:58]: Please remove it

**Review by dariadomagala — APPROVED** [review]

**Review by klaudiagrz — APPROVED** [review]
