### PR TITLE
fix: Preferences dialog UX adjustments

### LINKED ISSUE #4311: UXC-017 Settings - Preferences
## 🧩 UxC Vega Review Finding

**Context:**
As part of the **UxC Vega** product standards rollout, the UX team conducted a design review. The following finding requires adjustment to align with the new standards.

---

### 🔍 Finding Summary
**ID:** UXC-017

---

### 🧠 Description
- [x] Interface should be renamed to Appearance
- [x] Use the icon sap-icon://palette for the Interface
- [x] Language should be moved to a new page in the left navigation, under the Appearance tab
- [x] Use the icon sap-icon://globe for the Language
- [x] Move the default page size setting to the Clusters tab

---

### 📘 Reference
- **Design spec:** 
   - [Figma findings](https://www.figma.com/board/S23zo8HIqNvf2VuuLOp8ES/UXC-Reviews-2025?node-id=2705-5272&t=igqSHAXBj8bYYLYv-0)
- **Screenshot / Example:**  

Image

### LINKED ISSUE #4312: UXC-015, UXC-022 - Preferences
## 🧩 UxC Vega Review Finding

**Context:**
As part of the **UxC Vega** product standards rollout, the UX team conducted a design review. The following finding requires adjustment to align with the new standards.

---

### 🔍 Finding Summary
**ID:** UXC-015 UXC-022

---

### 🧠 Description
UXC-015 - Terminology and Standard Formulations
Discuss with UA if we should keep the naming Clusters, it feels that something like Kyma Settings or General is applicable too.

UXC-022 - Button
This button should be tertiary instead of secondary.

---

### 📘 Reference
- **Design spec:** 
   - [Figma findings](https://www.figma.com/board/S23zo8HIqNvf2VuuLOp8ES/UXC-Reviews-2025?node-id=2705-5289&t=igqSHAXBj8bYYLYv-0)
- **Screenshot / Example:**  

Image

### PR DESCRIPTION
**Pull request by awoloszyn22**
**Description**

Changes proposed in this pull request:

- Changed names and icons of left panel tabs in Preferences dialog, added Language tab
- Moved 'Default page setting (Others)' to the Settings tab
- Changed 'Close' button of the dialog to a tertiary one

**Related issue(s)**
Resolves #4311 
Resolves #4312

**Definition of done**

- [x] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - revert: Revert commit
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [x] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [x] Explain clearly why you created the PR and what changes it introduces
- [x] All necessary steps are delivered, for example, tests, documentation, merging

### CODE REVIEW

File: src/components/Preferences/ThemePreview/ThemePreview.tsx [hunk 1]
```diff
@@ -5,62 +5,72 @@ type ThemePreviewProps = {
   theme: Theme;
 };
 
+function ThemePreviewImage({ theme }: ThemePreviewProps) {
+  return (
+    // those are copied from https://sap.live.dxp.k8s.ondemand.com/projects
```
Comment (mrCherry97) [inline src/components/Preferences/ThemePreview/ThemePreview.tsx]:
```suggestion
    // Those are copied from https://sap.live.dxp.k8s.ondemand.com/projects
```

**Review by mrCherry97 — CHANGES_REQUESTED** [review]

**Review by grego952 — APPROVED** [review]

**Review by mrCherry97 — APPROVED** [review]
