### PR TITLE
fix: Undefined and many errors in console

### LINKED ISSUE #4356: Fix tons of the `undefined` from `useGetAllModulesStatuses`

### PR DESCRIPTION
**Pull request by KonradPietocha**
**Description**

Changes proposed in this pull request:

- Some code improvements

**Related issue(s)**

Closes #4356 

**Definition of done**

- [x] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - revert: Revert commit
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [x] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [x] Explain clearly why you created the PR and what changes it introduces
- [x] All necessary steps are delivered, for example, tests, documentation, merging

### CODE REVIEW

File: src/components/Extensibility/components/RadialChart.jsx [hunk 1]
```diff
@@ -49,11 +49,11 @@ export const RadialChart = ({ structure, value, originalResource }) => {
         color={structure.color}
         value={value}
         max={maxValue ? maxValue : structure?.maxValue}
-        titleText={t(structure?.name)}
+        titleText={t(structure?.name, structure?.name ?? '')}
```
Comment (dbadura) [inline src/components/Extensibility/components/RadialChart.jsx]: Shouldn't it be done this way?
```suggestion
        titleText={t(structure?.name, {defaultValue: structure?.name ?? ''})}
```

**Review by dbadura — APPROVED** [review]
