### PR TITLE
Fix incorrect Table Widget to not break the page 

### LINKED ISSUE #1440: Extensibility - incorrectly configured Table widget breaks the page
**Description**

The table widget breaks the page if it's configured incorrectly.
Example 
```
{
      "path": "metadata",
      "widget": "Table",
      "children": [{ "path": "name" }]
}
```

**Expected result**

It should show an error, or display the table partially.

**Actual result**

It breaks the page, with errors in the console
```Invalid prop `entries` of type `object` supplied to `GenericList`, expected an array.```
```entries.filter is not a function```

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by Lyczeq**
**Description**

Changes proposed in this pull request:

- Fixed the bug of incorrect Table Widget breaking the details page
- Added a key prop to remove console errors
- Added a prop to the GenericList component that is displayed when there's an incorrect extensibility configuration 
- Added translations

**Related issue(s)**
Resolves #1440

### CODE REVIEW

File: core-ui/src/components/Extensibility/components/Plain.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ export function Plain({ value, structure, schema }) {
   return (
     <div>
       {structure.children?.map(def => (
-        <Widget value={value} structure={def} schema={schema} />
+        <Widget value={value} structure={def} schema={schema} key={def} />
```
Comment (Wawrzyn321) [inline core-ui/src/components/Extensibility/components/Plain.js:9]: This won't do - since `def` is an object, the key would be always `[Object object]`.

File: core-ui/src/components/Extensibility/components/Table.js [hunk 2]
```diff
@@ -1,12 +1,33 @@
...
+import { useTranslation } from 'react-i18next';
 
 import { GenericList } from 'shared/components/GenericList/GenericList';
 
 import { useGetTranslation } from '../helpers';
 import { Widget } from './Widget';
 
+const handleTableValue = (value, t) => {
+  switch (true) {
+    case value === undefined: {
```
Comment (Wawrzyn321) [inline core-ui/src/components/Extensibility/components/Table.js:11]: Maybe use `isNil` from lodash to cover the `null` value?

File: core-ui/src/components/Extensibility/components/Table.js [hunk 3]
```diff
@@ -1,12 +1,33 @@
...
+    }
+    case Array.isArray(value): {
+      return {
+        entries: value,
+      };
+    }
+    default: {
+      return {
+        entries: [],
+        invalidConfigurationMessage: t('extensibility.widgets.table.error'),
```
Comment (Wawrzyn321) [inline core-ui/src/components/Extensibility/components/Table.js:22]: I'd go with less specific name here, so we can reuse this prop elsewhere. `genericErrorMessage`?

**Review by Wawrzyn321 — APPROVED** [review]
