### PR TITLE
fix switch context on cluster overview

### LINKED ISSUE #2359: Command-pallete all `ns all` on cluster overview
**Description**
On cluster overview in command-pallete is `Switch content` option where it should be.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by mrCherry97**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
Closes #2359

### CODE REVIEW

File: src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts [hunk 1]
```diff
@@ -187,6 +187,7 @@ function createResults(context: CommandPaletteContext): Result[] {
     activeClusterName,
     navigate,
   } = context;
+  console.log(window.location.pathname.includes('namespaces'));
```
Comment (akucharska) [inline src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts:190]: remove console.log

**Review by akucharska — APPROVED** [review]
