### PR TITLE
fix: refreshing app when changing namespace

### LINKED ISSUE #2155: Page refresh after going to namespace details
**Description**
Clicking on namespace in namespace list creates a full page refresh.

**Expected result**

**Actual result**

**Steps to reproduce**
1. Connect cluster
2. Namespaces
3. Click on namespace to go on details view

**Troubleshooting**

### PR DESCRIPTION
**Pull request by Lyczeq**
**Description**

Changes proposed in this pull request:

- add translated error message for sidebar navigation
- add styles to display the message correctly depending on current theme
- add Suspense to Sidebar to wait until the nodes are loaded
- fix codeowners file

**Related issue(s)**
Resolves #2155

### CODE REVIEW

File: core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.js [hunk 1]
```diff
@@ -24,7 +25,7 @@ class ErrorBoundaryComponent extends React.Component {
     if (this.state.hasError) {
       return (
         <div role="alert">
-          <p className="fd-margin-top-bottom--sm">
+          <p className="fd-margin-top-bottom--sm error-message">
```
Comment (mrCherry97) [inline core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.js:28]:
```suggestion
          <p className="fd-margin-top-bottom--sm error-message fd-color--warning">
```

File: core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.js [hunk 2]
```diff
@@ -2,6 +2,7 @@ import React from 'react';
 import { Button } from 'fundamental-react';
 import { useTranslation } from 'react-i18next';
 import * as Sentry from '@sentry/react';
+import './ErrorBoundary.scss';
```
Comment (mrCherry97) [inline core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.js:5]: Can be removed, let's have a talk later

File: core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.scss [hunk 3]
```diff
@@ -0,0 +1,3 @@
+.error-message {
+  color: var(--sapTextColor);
+}
```
Comment (mrCherry97) [inline core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.scss:3]: Can be removed, let's have a talk later

**Review by mrCherry97 — CHANGES_REQUESTED** [review]

**Review by mrCherry97 — APPROVED** [review]
/woof
