### PR TITLE
Fix automatically adding null to yaml editor

### LINKED ISSUE #1288: empty strings are replaced with null
**Description**

When you remove a value in monaco editor, Busola inserts null in its place, that you need to manually replace with a new text

The screen shows the "Connect cluster" view, but it happens in a lot of other places. 

**Expected result**
When a value is removed, nothing happens

**Actual result**

When a value is removed, null is inserted

**Steps to reproduce**

image

### PR DESCRIPTION
**Pull request by dariadomagala**
**Description**

Changes proposed in this pull request:

- Fix automatically adding null to yaml editor when typing
- ...
- ...

**Related issue(s)**

Resolves #1288

### CODE REVIEW

**Review by mrCherry97 — CHANGES_REQUESTED** [review]
Doesn't work in Adding Cluster wizard
image

File: core-ui/src/resources/Namespaces/YamlUpload/YamlUploadDialog.js [hunk 1]
```diff
@@ -49,17 +50,22 @@ export function YamlUploadDialog({ show, onCancel }) {
...
+      const nonEmptyResources = yaml?.filter(resource => resource !== null);
+      const resourcesWithStatus = nonEmptyResources?.map(value => ({
+        value,
+        status: '',
+        message: '',
+      }));
+      setResourcesWithStatuses(resourcesWithStatus);
+      oldYaml.current = yaml;
+    } catch ({ message }) {
+      console.log(message);
```
Comment (mrCherry97) [inline core-ui/src/resources/Namespaces/YamlUpload/YamlUploadDialog.js:67]: Maybe a better option is `console.error` ?

**Review by wchrapka — DISMISSED** [review]

**Review by mrCherry97 — APPROVED** [review]

**Review by wchrapka — APPROVED** [review]
