### PR TITLE
Fix css in timeframe-fn-logs

### LINKED ISSUE #870: Filter timeframe in function logs is broken
**Description**
Filter timeframe in function logs is broken and goes out of frame.

**Expected result**
Filter timeframe in function logs works well and is displayed in a frame.

**Actual result**
Chrome:
image

Safari:
image

Firefox:
image

**Steps to reproduce**
1. Connect cluster
2. Go to the namespace or create the namespace
3. Go to `Workloads -> Functions`
4. Create a function
5. Go to logs

**Troubleshooting**

### PR DESCRIPTION
**Pull request by wchrapka**
**Description**

Fix css timeframe function logs

**Related issue(s)**
Fixes #870

### CODE REVIEW

File: core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js [hunk 1]
```diff
@@ -179,10 +179,10 @@ export const ContainersLogs = ({ params }) => {
         <PageHeader
           title={params.containerName}
           breadcrumbItems={breadcrumbs}
-        ></PageHeader>
+        />
       </div>
       <LayoutPanel className="fd-margin--md logs-panel">
-        <LayoutPanel.Header>
+        <LayoutPanel.Header className="logs-panel-header">
```
Comment (dariadomagala) [inline core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js:185]: Wouldn't it be better to have a smaller dropdown (all entries in the dropdown are short) and fir everything into one line?

**Review by dariadomagala — APPROVED** [review]
