### PR TITLE
fix: Adjust buttons in headers

### LINKED ISSUE #4287: UXC-014 Action Placement - Namespace Overview
## 🧩 UxC Vega Review Finding

**Context:**
As part of the **UxC Vega** product standards rollout, the UX team conducted a design review. The following finding requires adjustment to align with the new standards.

---

### 🔍 Finding Summary
**ID:** UXC-014

---

### 🧠 Description
- [x] Move the “Discover Logs” button after the “Upload YAML” button. (Extensibility Injections need to be moved after `Upload YAML`)
- [x] The tables shouldn’t have emphasized buttons. (Limit Range and Resource Quota)

---

### 📘 Reference
- **Design spec:** 
   - [Figma findings](https://www.figma.com/board/S23zo8HIqNvf2VuuLOp8ES/UXC-Reviews-2025?node-id=1967-691&t=bqTrM4ZQBdZcd1NW-0)
- **Screenshot / Example:**  

Image

### LINKED ISSUE #4302: UXC-015 Terminology - Connect Cluster
## 🧩 UxC Vega Review Finding

**Context:**
As part of the **UxC Vega** product standards rollout, the UX team conducted a design review. The following finding requires adjustment to align with the new standards.

---

### 🔍 Finding Summary
**ID:** UXC-015

---

### 🧠 Description
Button text should be title case: `Connect Cluster`

---

### 📘 Reference
- **Design spec:** 
   - [Figma findings](https://www.figma.com/board/S23zo8HIqNvf2VuuLOp8ES/UXC-Reviews-2025?node-id=2705-4981&t=igqSHAXBj8bYYLYv-0)
   - **Screenshot / Example:**  

Image

### PR DESCRIPTION
**Pull request by OliwiaGowor**
**Description**

Changes proposed in this pull request:

- Moved extensibility injections in headers after default action buttons
- Adjusted buttons on Cluster Overview
- Changed `Connect Cluster` button

**Related issue(s)**
Closes #4287 , closes #4302 

**Definition of done**

- [x] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - revert: Revert commit
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [x] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [x] Explain clearly why you created the PR and what changes it introduces
- [x] All necessary steps are delivered, for example, tests, documentation, merging

### CODE REVIEW

File: src/resources/LimitRanges/LimitRangesList.jsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ export function LimitRangesList(props) {
     <ToolbarButton
       key={`create-limit-ranges`}
       data-testid={`create-limit-ranges`}
-      design="Emphasized"
+      design="Default"
```
Comment (dbadura) [inline src/resources/LimitRanges/LimitRangesList.jsx]: Desing by default is default: https://ui5.github.io/webcomponents/components/ToolbarButton/#design
Applies to all buttons

**Review by dbadura — CHANGES_REQUESTED** [review]
